
export const hcBench = [
  {"id": "07d3d4d8", "name": "Bench at Nagpur"},
  {"id": "0b2364ce", "name": "Principal Bench at Hyderabad"},
  {"id": "0ba5ccaf", "name": "Principal Bench at Delhi"},
  {"id": "0ec192c0", "name": "Principal Bench Jharkhand"},
  {"id": "0f93aee6", "name": "Circuit Bench At Port Blair"},
  {"id": "1057d81a", "name": "High Court Of Madhya Pradesh Gwalior"},
  {"id": "13bfb5f0", "name": "Itanagar Bench"},
  {"id": "159b0f6b", "name": "High Court of Punjab and Haryana"},
  {"id": "1f0d8728", "name": "High Court of Meghalaya"},
  {"id": "2b51daa5", "name": "Bench at Kalburagi"},
  {"id": "3254289f", "name": "Kohima Bench"},
  {"id": "34fa1bd4", "name": "Principal Bench of Madras High Court"},
  {"id": "3d4109bc", "name": "Appellate side"},
  {"id": "412a4789", "name": "Original Side,Bombay"},
  {"id": "47041251", "name": "High Court of Tripura"},
  {"id": "4a0e2871", "name": "High Court Of Madhya Pradesh Jabalpur"},
  {"id": "4ab6a0ad", "name": "High Court of Orissa"},
  {"id": "4caaa93f", "name": "High Court of Kerala"},
  {"id": "59510d91", "name": "Appellate Side,Bombay"},
  {"id": "5b4829fc", "name": "Allahabad High Court Lucknow Bench"},
  {"id": "632910ed", "name": "High Court Of Madhya Pradesh Indore"},
  {"id": "73e23b44", "name": "Principal Bench at Bengaluru"},
  {"id": "7a0bd384", "name": "Circuit Bench At Jalpaiguri"},
  {"id": "87b26481", "name": "High Court Bench at Jaipur"},
  {"id": "890e372d", "name": "High Court of Sikkim"},
  {"id": "8dcad33a", "name": "Rajasthan High Court Principal Seat Jodhpur"},
  {"id": "90cddac9", "name": "Aizawl Bench"},
  {"id": "a16dc3c3", "name": "Special Court (TORTS) Bombay"},
  {"id": "a89e566a", "name": "High Court of Uttarakhand"},
  {"id": "ae5dd0c8", "name": "High Court of Himachal Pradesh"},
  {"id": "b9638ec5", "name": "High Court of Manipur"},
  {"id": "c19f98d8", "name": "Principal Seat at Guwahati"},
  {"id": "c449b56c", "name": "Srinagar Wing"},
  {"id": "c9240e48", "name": "Jammu Wing"},
  {"id": "cd7da774", "name": "Bench at Dharwad"},
  {"id": "cee2e005", "name": "Principal Bench Patna"},
  {"id": "e2433ac3", "name": "Principlal Bench at Andhra Pradesh"},
  {"id": "eb81b29e", "name": "High court of Bombay at Goa"},
  {"id": "f261d3d4", "name": "Bench at Aurangabad"},
  {"id": "f3a2577b", "name": "Original Side"},
  {"id": "f7eda34e", "name": "Gujarat High Court"},
  {"id": "f7f94530", "name": "Madurai Bench of Madras High Court"},
  {"id": "fb746078", "name": "Allahabad High Court"},
  {"id": "ffc96b04", "name": "Principal Bench Chhattisgarh"}
]
